class TeamNamesPt {
  static const Map<String, String> _names = {
    // CONMEBOL
    'Brazil': 'Brasil',
    'Argentina': 'Argentina',
    'Uruguay': 'Uruguai',
    'Colombia': 'Colômbia',
    'Ecuador': 'Equador',
    'Peru': 'Peru',
    'Chile': 'Chile',
    'Venezuela': 'Venezuela',
    'Paraguay': 'Paraguai',
    'Bolivia': 'Bolívia',

    // UEFA
    'Germany': 'Alemanha',
    'France': 'França',
    'Spain': 'Espanha',
    'England': 'Inglaterra',
    'Portugal': 'Portugal',
    'Netherlands': 'Holanda',
    'Belgium': 'Bélgica',
    'Italy': 'Itália',
    'Croatia': 'Croácia',
    'Denmark': 'Dinamarca',
    'Switzerland': 'Suíça',
    'Austria': 'Áustria',
    'Serbia': 'Sérvia',
    'Scotland': 'Escócia',
    'Turkey': 'Turquia',
    'Slovakia': 'Eslováquia',
    'Czech Republic': 'República Checa',
    'Hungary': 'Hungria',
    'Albania': 'Albânia',
    'Slovenia': 'Eslovênia',
    'Georgia': 'Geórgia',
    'Iceland': 'Islândia',
    'Ukraine': 'Ucrânia',
    'Romania': 'Romênia',
    'Norway': 'Noruega',
    'Sweden': 'Suécia',
    'Finland': 'Finlândia',
    'Wales': 'País de Gales',
    'Northern Ireland': 'Irlanda do Norte',
    'Ireland': 'Irlanda',
    'Poland': 'Polônia',
    'Greece': 'Grécia',
    'Russia': 'Rússia',
    'North Macedonia': 'Macedônia do Norte',
    'Montenegro': 'Montenegro',
    'Kosovo': 'Kosovo',
    'Bosnia': 'Bósnia',
    'Bosnia & Herzegovina': 'Bósnia',
    'Bosnia and Herzegovina': 'Bósnia',
    'Bulgaria': 'Bulgária',
    'Estonia': 'Estônia',
    'Latvia': 'Letônia',
    'Lithuania': 'Lituânia',
    'Luxembourg': 'Luxemburgo',
    'Malta': 'Malta',
    'Moldova': 'Moldávia',
    'Armenia': 'Armênia',
    'Azerbaijan': 'Azerbaijão',
    'Kazakhstan': 'Cazaquistão',
    'Belarus': 'Bielorrússia',
    'Liechtenstein': 'Liechtenstein',

    // CONCACAF
    'United States': 'Estados Unidos',
    'USA': 'EUA',
    'Mexico': 'México',
    'Canada': 'Canadá',
    'Panama': 'Panamá',
    'Costa Rica': 'Costa Rica',
    'Honduras': 'Honduras',
    'El Salvador': 'El Salvador',
    'Jamaica': 'Jamaica',
    'Trinidad and Tobago': 'Trinidad e Tobago',
    'Trinidad & Tobago': 'Trinidad e Tobago',
    'Curacao': 'Curaçao',
    'Guatemala': 'Guatemala',
    'Cuba': 'Cuba',
    'Haiti': 'Haiti',
    'Nicaragua': 'Nicarágua',
    'Dominican Republic': 'Rep. Dominicana',

    // Seleções históricas (nomes desatualizados da API)
    'West Germany': 'Alemanha Oc.',
    'East Germany': 'Alemanha Or.',
    'Soviet Union': 'União Soviética',
    'Yugoslavia': 'Iugoslávia',
    'Czechoslovakia': 'Tchecoslováquia',
    'Zaire': 'Zaire',
    'United Arab Emirates': 'Emirados Árabes',
    "Côte d'Ivoire": 'Costa do Marfim',
    'Serbia and Montenegro': 'Sérvia e Mont.',
    'Bosnia-Herzegovina': 'Bósnia',
    'Dutch East Indies': 'Índias Orient.',

    // CAF
    'Morocco': 'Marrocos',
    'Senegal': 'Senegal',
    'Nigeria': 'Nigéria',
    'Cameroon': 'Camarões',
    'Ghana': 'Gana',
    'Egypt': 'Egito',
    'Tunisia': 'Tunísia',
    'Algeria': 'Argélia',
    'Ivory Coast': 'Costa do Marfim',
    'Mali': 'Mali',
    'South Africa': 'África do Sul',
    'Congo DR': 'Rep. Congo',
    'DR Congo': 'Rep. Congo',
    'Congo': 'Congo',
    'Burkina Faso': 'Burkina Faso',
    'Guinea': 'Guiné',
    'Tanzania': 'Tanzânia',
    'Zambia': 'Zâmbia',
    'Zimbabwe': 'Zimbábue',
    'Mozambique': 'Moçambique',
    'Angola': 'Angola',
    'Ethiopia': 'Etiópia',
    'Kenya': 'Quênia',
    'Uganda': 'Uganda',
    'Rwanda': 'Ruanda',
    'Cape Verde': 'Cabo Verde',
    'Togo': 'Togo',
    'Benin': 'Benim',
    'Namibia': 'Namíbia',
    'Libya': 'Líbia',
    'Sudan': 'Sudão',
    'Somalia': 'Somália',
    'Sierra Leone': 'Serra Leoa',
    'Liberia': 'Libéria',
    'Gabon': 'Gabão',
    'Equatorial Guinea': 'Guiné Equatorial',
    'Gambia': 'Gâmbia',
    'South Sudan': 'Sudão do Sul',
    'Botswana': 'Botsuana',

    // AFC
    'Japan': 'Japão',
    'South Korea': 'Coreia do Sul',
    'Australia': 'Austrália',
    'Saudi Arabia': 'Arábia Saudita',
    'Iran': 'Irã',
    'Qatar': 'Catar',
    'Iraq': 'Iraque',
    'Jordan': 'Jordânia',
    'Indonesia': 'Indonésia',
    'Uzbekistan': 'Uzbequistão',
    'China': 'China',
    'China PR': 'China',
    'Thailand': 'Tailândia',
    'Vietnam': 'Vietnã',
    'India': 'Índia',
    'Bahrain': 'Barein',
    'Kuwait': 'Kuwait',
    'Oman': 'Omã',
    'Syria': 'Síria',
    'Lebanon': 'Líbano',
    'Israel': 'Israel',
    'Palestine': 'Palestina',
    'North Korea': 'Coreia do Norte',
    'Myanmar': 'Mianmar',

    // OFC
    'New Zealand': 'Nova Zelândia',
    'Papua New Guinea': 'Papua-Nova Guiné',
    'Fiji': 'Fiji',
    'Solomon Islands': 'Ilhas Salomão',
    'Vanuatu': 'Vanuatu',
    'Samoa': 'Samoa',
    'Tonga': 'Tonga',
    'Tahiti': 'Taiti',
  };

  static const Map<String, String> _rounds = {
    'Matchday 1': 'Rodada 1',
    'Matchday 2': 'Rodada 2',
    'Matchday 3': 'Rodada 3',
    'Round of 32': 'Rodada de 32',
    'Round of 16': 'Oitavas de Final',
    'Quarter-final': 'Quartas de Final',
    'Quarter-finals': 'Quartas de Final',
    'Semi-final': 'Semifinais',
    'Semi-finals': 'Semifinais',
    'Match for third place': 'Disputa 3º Lugar',
    'Third-place match': 'Disputa 3º Lugar',
    'Third-place play-off': 'Disputa 3º Lugar',
    'Play-off for third place': 'Disputa 3º Lugar',
    'Final': 'Final',
  };

  static const Map<String, String> _continents = {
    'North America': 'América do Norte',
    'South America': 'América do Sul',
    'Europe': 'Europa',
    'Africa': 'África',
    'Asia': 'Ásia',
    'Oceania': 'Oceania',
  };

  static String continent(String c) => _continents[c] ?? c;

  static String translate(String name) => _names[name] ?? name;

  static String round(String r) => _rounds[r] ?? r;

  static String group(String g) =>
      g.startsWith('Group ') ? 'Grupo ${g.substring(6)}' : g;
}
