class TeamFlags {
  static const Map<String, String> _map = {
    'Algeria': '🇩🇿',
    'Angola': '🇦🇴',
    'Argentina': '🇦🇷',
    'Armenia': '🇦🇲',
    'Australia': '🇦🇺',
    'Austria': '🇦🇹',
    'Azerbaijan': '🇦🇿',
    'Bahrain': '🇧🇭',
    'Belgium': '🇧🇪',
    'Bolivia': '🇧🇴',
    'Bosnia': '🇧🇦',
    'Bosnia & Herzegovina': '🇧🇦',
    'Bosnia and Herzegovina': '🇧🇦',
    'Bosnia-Herzegovina': '🇧🇦',
    'Brazil': '🇧🇷',
    'Bulgaria': '🇧🇬',
    'Burkina Faso': '🇧🇫',
    'Cameroon': '🇨🇲',
    'Canada': '🇨🇦',
    'Cape Verde': '🇨🇻',
    'Chile': '🇨🇱',
    'China': '🇨🇳',
    'China PR': '🇨🇳',
    'Colombia': '🇨🇴',
    'Congo DR': '🇨🇩',
    "Côte d'Ivoire": '🇨🇮',
    'Czechoslovakia': '🇨🇿',
    'DR Congo': '🇨🇩',
    'Dutch East Indies': '🇮🇩',
    'Costa Rica': '🇨🇷',
    'Croatia': '🇭🇷',
    'Cuba': '🇨🇺',
    'Curacao': '🇨🇼',
    'Czech Republic': '🇨🇿',
    'Denmark': '🇩🇰',
    'Dominican Republic': '🇩🇴',
    'Ecuador': '🇪🇨',
    'East Germany': '🇩🇪',
    'Egypt': '🇪🇬',
    'El Salvador': '🇸🇻',
    'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    'Equatorial Guinea': '🇬🇶',
    'Estonia': '🇪🇪',
    'Ethiopia': '🇪🇹',
    'Finland': '🇫🇮',
    'France': '🇫🇷',
    'Gabon': '🇬🇦',
    'Gambia': '🇬🇲',
    'Georgia': '🇬🇪',
    'Germany': '🇩🇪',
    'Ghana': '🇬🇭',
    'Greece': '🇬🇷',
    'Guatemala': '🇬🇹',
    'Guinea': '🇬🇳',
    'Guyana': '🇬🇾',
    'Haiti': '🇭🇹',
    'Honduras': '🇭🇳',
    'Hungary': '🇭🇺',
    'Iceland': '🇮🇸',
    'Indonesia': '🇮🇩',
    'Iran': '🇮🇷',
    'Iraq': '🇮🇶',
    'Ireland': '🇮🇪',
    'Israel': '🇮🇱',
    'Italy': '🇮🇹',
    'Ivory Coast': '🇨🇮',
    'Jamaica': '🇯🇲',
    'Japan': '🇯🇵',
    'Jordan': '🇯🇴',
    'Kazakhstan': '🇰🇿',
    'Kenya': '🇰🇪',
    'Kosovo': '🇽🇰',
    'Kuwait': '🇰🇼',
    'Latvia': '🇱🇻',
    'Lebanon': '🇱🇧',
    'Liberia': '🇱🇷',
    'Libya': '🇱🇾',
    'Liechtenstein': '🇱🇮',
    'Lithuania': '🇱🇹',
    'Luxembourg': '🇱🇺',
    'Madagascar': '🇲🇬',
    'Malawi': '🇲🇼',
    'Mali': '🇲🇱',
    'Malta': '🇲🇹',
    'Mauritania': '🇲🇷',
    'Mexico': '🇲🇽',
    'Moldova': '🇲🇩',
    'Montenegro': '🇲🇪',
    'Morocco': '🇲🇦',
    'Mozambique': '🇲🇿',
    'Namibia': '🇳🇦',
    'Netherlands': '🇳🇱',
    'New Zealand': '🇳🇿',
    'Nicaragua': '🇳🇮',
    'Niger': '🇳🇪',
    'Nigeria': '🇳🇬',
    'North Korea': '🇰🇵',
    'North Macedonia': '🇲🇰',
    'Northern Ireland': '🇬🇧',
    'Norway': '🇳🇴',
    'Oman': '🇴🇲',
    'Panama': '🇵🇦',
    'Paraguay': '🇵🇾',
    'Peru': '🇵🇪',
    'Poland': '🇵🇱',
    'Portugal': '🇵🇹',
    'Qatar': '🇶🇦',
    'Romania': '🇷🇴',
    'Russia': '🇷🇺',
    'Rwanda': '🇷🇼',
    'Saudi Arabia': '🇸🇦',
    'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    'Senegal': '🇸🇳',
    'Serbia': '🇷🇸',
    'Serbia and Montenegro': '🇷🇸',
    'Sierra Leone': '🇸🇱',
    'Slovakia': '🇸🇰',
    'Slovenia': '🇸🇮',
    'Somalia': '🇸🇴',
    'Soviet Union': '🇷🇺',
    'South Africa': '🇿🇦',
    'South Korea': '🇰🇷',
    'South Sudan': '🇸🇸',
    'Spain': '🇪🇸',
    'Sudan': '🇸🇩',
    'Suriname': '🇸🇷',
    'Sweden': '🇸🇪',
    'Switzerland': '🇨🇭',
    'Syria': '🇸🇾',
    'Tanzania': '🇹🇿',
    'Thailand': '🇹🇭',
    'Togo': '🇹🇬',
    'Trinidad and Tobago': '🇹🇹',
    'Trinidad & Tobago': '🇹🇹',
    'Tunisia': '🇹🇳',
    'Turkey': '🇹🇷',
    'Uganda': '🇺🇬',
    'Ukraine': '🇺🇦',
    'United Arab Emirates': '🇦🇪',
    'United States': '🇺🇸',
    'Uruguay': '🇺🇾',
    'USA': '🇺🇸',
    'Uzbekistan': '🇺🇿',
    'Venezuela': '🇻🇪',
    'Vietnam': '🇻🇳',
    'Wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    'West Germany': '🇩🇪',
    'Yemen': '🇾🇪',
    'Yugoslavia': '🇷🇸',
    'Zaire': '🇨🇩',
    'Zambia': '🇿🇲',
    'Zimbabwe': '🇿🇼',
  };

  static String get(String teamName) {
    return _map[teamName] ?? _map[teamName.trim()] ?? '';
  }

  static String flagOrEmpty(String teamName) => get(teamName);
}
